spring:
  application:
    name: RuleEngine

  output:
    ansi:
      enabled: always

  kafka:
    bootstrap-servers: localhost:9092
    client-id: rule-engine
    consumer:
      group-id: default
      auto-offset-reset: earliest

app:
  conditions:
    enabled: true
    path: classpath:conditions.json
  transformations:
    enabled: true
    path: classpath:transformations.json
